version: '3.4'

services:
  # PostgreSQL database
  event-postgres-db:
    image: postgres:14.0
    container_name: postgres-event
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 20s
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./.docker/postgres/pg_data:/var/lib/postgresql/data

  # RabbitMQ
  event-rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-event
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
    environment:
      RABBITMQ_DEFAULT_USER: event
      RABBITMQ_DEFAULT_PASS: event
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq/
