# Spring configuration
spring:
  application:
    name: event
  datasource:
    url: jdbc:postgresql://localhost:5432/docker_and_testcontainer_db
    username: docker_and_testcontainer_user
    password: docker_and_testcontainer_password
  jpa:
    database: postgresql
    open-in-view: false
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: docker_and_testcontainer_user
    password: docker_and_testcontainer_password

# Server configuration
server:
  port: 8585
  servlet:
    context-path: /event

# Rest clients
rest-client:
  discount:
    url: http://localhost:8080
